In [59]:
a=0.4
p=0.8
import numpy as np

def C(a):
    return 2*a**2
def aa(a, p):
    return 1-p
def b(a, p):
    return 2*(1-p)+(1-C(a))*p/2
def c(a, p):
    return 1-p+(1-C(a))*p
def d(a, p):
    return -1.5*(1-C(a))*p
def delta0(a, p):
    return b(a, p)**2-3*aa(a, p)*c(a, p)
def delta1(a, p):
    return 2*b(a, p)**3-9*aa(a, p)*b(a, p)*c(a, p)+27*aa(a, p)**2*d(a, p)
def C1(a, p):
    temp1=(delta1(a, p)**2-4*delta0(a, p)**3)**0.5
    temp2=(delta1(a, p)+temp1)/2
    return temp2**(1/3)
def x1(a, p):
    return -(b(a, p)+C1(a, p)+delta0(a, p)/C1(a, p))/(3*aa(a, p))
def C2(a, p):
    return (-0.5+0.5*(-3)**0.5)*C1(a, p)
def x2(a, p):
    return -(b(a, p)+C2(a, p)+delta0(a, p)/C2(a, p))/(3*aa(a, p))
def C3(a, p):
    return (-0.5-0.5*(-3)**0.5)*C1(a, p)
def x3(a, p):
    return -(b(a, p)+C3(a, p)+delta0(a, p)/C3(a, p))/(3*aa(a, p))
def cstage(a, p):
    return np.asarray([x2(a, p).real])

In [60]:
cstage(0.3, 0.7)

array([ 0.5787377])

In [55]:
np.asarray([0.2])

array([ 0.2])

In [47]:
from scipy.optimize import fsolve
def lhs(sigma):
    temp1=1.5-(sigma+sigma**2/2)
    temp2=sigma*(1+sigma)**2
    return temp1/temp2
#rhs of static condition
def rhs(a, p):
    temp1=1-p
    temp2=(1-C(a))*p
    return temp1/temp2
#express critical stage as function of a and p
def cstage(a, p):
    rrhs=rhs(a, p)
    def lhsminusrhs(sigma):
        return lhs(sigma)-rrhs
    return fsolve(lhsminusrhs, 0.5)
cstage(0.2, 0.9)

array([ 0.82609247])

In [48]:
timeit cstage(0.2, 0.9)

1000 loops, best of 3: 239 µs per loop


In [49]:
timeit x2(0.2, 0.9)

10000 loops, best of 3: 44.3 µs per loop


In [62]:
from scipy.optimize import fminbound
#left hand side of static condition
def lhs(sigma):
    temp1=1.5-(sigma+sigma**2/2)
    temp2=sigma*(1+sigma)**2
    return temp1/temp2
#rhs of static condition
def rhs(a, p):
    temp1=1-p
    temp2=(1-C(a))*p
    return temp1/temp2
#express critical stage as function of a and p
def cstage(a, p):
    rrhs=rhs(a, p)
    def lhsminusrhs(sigma):
        return (lhs(sigma)-rrhs)**2
    return fminbound(lhsminusrhs, 1e-6, 1)
cstage(0.3, 0.6)

0.49123074979370218